# Generated by Django 3.2.8 on 2021-11-07 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='playList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=255, unique=True)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='songModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=255)),
                ('song', models.CharField(max_length=255)),
                ('uri', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='roomInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ready_player', models.IntegerField(default=0)),
                ('max_player', models.IntegerField(default=8)),
                ('max_song', models.IntegerField(default=10)),
                ('guess_time', models.IntegerField(default=15)),
                ('player', models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotifymusicgame.playlist')),
            ],
        ),
        migrations.AddField(
            model_name='playlist',
            name='song_list',
            field=models.ManyToManyField(related_name='playlist', to='spotifymusicgame.songModel'),
        ),
        migrations.CreateModel(
            name='played',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('max_score', models.IntegerField(default=10)),
                ('played', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotifymusicgame.roominfo')),
            ],
        ),
    ]
