# Generated by Django 3.2.8 on 2021-10-31 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotifymusicgame', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='songModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=100)),
                ('images', models.CharField(max_length=255)),
                ('song_name', models.CharField(max_length=255)),
                ('uri', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='playlist',
            name='url',
            field=models.URLField(max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='playlist',
            name='song',
            field=models.ManyToManyField(to='spotifymusicgame.songModel'),
        ),
    ]
