# Generated by Django 3.2.7 on 2021-11-05 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotifymusicgame', '0002_remove_roominfo_ready_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='roominfo',
            name='ready_player',
            field=models.IntegerField(default=8),
        ),
    ]
