# Generated by Django 3.2.7 on 2021-11-13 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotifymusicgame', '0002_auto_20211112_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='roominfo',
            name='is_playing',
            field=models.BooleanField(default=False),
        ),
    ]
