# Generated by Django 3.2.8 on 2021-10-31 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotifymusicgame', '0002_auto_20211031_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='song',
            field=models.ManyToManyField(blank=True, null=True, to='spotifymusicgame.songModel'),
        ),
    ]
