# Generated by Django 3.2.7 on 2021-11-06 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotifymusicgame', '0003_roominfo_ready_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roominfo',
            name='ready_player',
            field=models.IntegerField(default=0),
        ),
    ]
