# Generated by Django 3.2.8 on 2021-10-31 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotifymusicgame', '0003_alter_playlist_song'),
    ]

    operations = [
        migrations.RenameField(
            model_name='songmodel',
            old_name='images',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='songmodel',
            old_name='song_name',
            new_name='song',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='song',
        ),
    ]
