# Generated by Django 3.2.8 on 2021-11-07 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotifymusicgame', '0003_roominfo_ready_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roominfo',
            name='ready_player',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='songmodel',
            name='uri',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
