# Generated by Django 3.2.8 on 2021-10-31 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotifymusicgame', '0004_auto_20211031_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='song_list',
            field=models.ManyToManyField(to='spotifymusicgame.songModel'),
        ),
    ]
