# Generated by Django 3.2.8 on 2021-10-31 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotifymusicgame', '0005_playlist_song_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='song_list',
            field=models.ManyToManyField(related_name='playlist', to='spotifymusicgame.songModel'),
        ),
    ]
